spring.application.name=productos
# Puerto del backend
# ===== Conexión a PostgreSQL =====
# Buena práctica: leer datos sensibles de variables de entorno.
# Si la variable no existe, usa el valor que va después de los dos puntos.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/productos_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Ederjesus_0805}
# ===== JPA / Hibernate =====
# update: crea o actualiza las tablas según las entidades
spring.jpa.hibernate.ddl-auto=update
# Muestra en consola el SQL que ejecuta Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# URL del frontend que tiene permiso de llamar a la API (CORS)
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:4200}